neutrons/Shiver

src/shiver/models/makeslice.py
This means the order of importing is less important. You can import `mantid.simpleapi` before you register the new function.
=> Make sure MakeSlice is available in simpleapi

src/shiver/models/histogram.py, src/shiver/presenters/histogram.py, src/shiver/shiver.py, src/shiver/views/histogram.py, src/shiver/views/mainwindow.py, tests/views/test_histogram.py
This PR added the viewer (QListWidget) for MDE and normalization workspaces.
Test instructions
============
- setup dev env and clone the feature branch (perform editable install if necessary)
- start shiver
- load the test data set by clicking `Load_MDE`
- the workspace name should appear in the first column (given test mde data evaluate to false when checking `isMDHistoWorkspace()`)
> IBM item: [Story587](https://ornlrse.clm.ibmcloud.com/ccm/web/projects/Neutron%20Data%20Project%20(Change%20Management)#action=com.ibm.team.workitem.viewWorkItem&id=587)
=> Add workspace tables (QListWidgets)

src/shiver/views/histogram.py
They should now look like this
=> Rearrange input workspace tables

src/shiver/views/workspace_tables.py, tests/views/test_mde_workspaces.py
Adding tests to the MDE workspace menu for "Set as Data", "Set as Background", "Rename" and "Delete".
[933](https://ornlrse.clm.ibmcloud.com/ccm/web/projects/Neutron%20Data%20Project%20(Change%20Management)#action=com.ibm.team.workitem.viewWorkItem&id=933)
=> Update context menu connection, allow it to be testable, and add tests

src/shiver/models/corrections.py, src/shiver/models/histogram.py, src/shiver/presenters/histogram.py, src/shiver/views/corrections.py, src/shiver/views/histogram.py, src/shiver/views/workspace_tables.py, tests/conftest.py, tests/views/test_correction.py, tests/views/test_histogram.py, tests/views/test_mde_workspaces.py
Description
========
- add correction table for MDE workspaces
- add corresponding unit test
Testing instruction
==============
- clone the feature branch and perform editable install with pip (see readme.md)
- start the application by typing `shiver` in the CML
- happy path
- load an mde workspace
- right click and select `set corrections`  
- config the correction table to match below
- hit `Apply` or enter on the keyboard
- a new workspace should be visible from the mde list, and the correction tab should be gone automatically
> IBM work item: [Story588](https://ornlrse.clm.ibmcloud.com/ccm/web/projects/Neutron%20Data%20Project%20(Change%20Management)#action=com.ibm.team.workitem.viewWorkItem&id=588)
=> Add correction table

src/shiver/shiver.py
This will fix issues where widgets are deleted after closing and the application crashing when reopening Shiver
If you start Shiver from the workbench, then close it and open it again, when you load a valid file you would get the following error:
```RuntimeError: CreateMDHistoWorkspace-v1: wrapped C/C++ object of type MDEList has been deleted
at line 172 in '/home/rwp/src/DGS_SC_scripts/src/shiver/models/histogram.py'
caused by line 167 in '/home/rwp/src/DGS_SC_scripts/src/shiver/models/histogram.py'
caused by line 56 in '/home/rwp/src/DGS_SC_scripts/src/shiver/presenters/histogram.py'
caused by line 55 in '/home/rwp/src/DGS_SC_scripts/src/shiver/views/histogram.py'
caused by line 45 in '/home/rwp/src/DGS_SC_scripts/src/shiver/views/workspace_tables.py'
caused by line 69 in …
```
=> Make the main Shiver window a singleton

src/shiver/views/histogram_parameters.py, tests/views/test_dimensions.py
Description
---------------
- when swapping dimension in the parameter table, the corresponding min/max/step is also swapped
- step value is retain even if it is not visible
- adjust the config file parser (for `MakeSlice`) to accommodate the recent change
To Test
----------
- Clone the repo and shiver
- Input some values in the parameter table and start swapping the dimensions
- The min/max/step value should also be auto swapped
- Perform a data reduction with `MakeSlice` and make sure the history is using correct parameters.  
> IBM item: [957](https://ornlrse.clm.ibmcloud.com/ccm/web/projects/Neutron%20Data%20Project%20(Change%20Management)#action=com.ibm.team.workitem.viewWorkItem&id=957)
=> Enable auto swapping min/max/step and retain step value

src/shiver/models/histogram.py, src/shiver/presenters/histogram.py, src/shiver/views/histogram_parameters.py, src/shiver/views/workspace_tables.py, tests/models/test_gather_history.py, tests/views/test_histogram.py
- If a histogram workspace is generated with MakeSlice and present in the MDH column (right most), clicking on the name of the workspace will auto populate the histogram UI based on the history information from the MakeSlice algorithm.
To Test
---------
- Clone the feature branch and setup shiver as instructed in Readme
- Load the test MDE data and rename it to test1, test2
- Load the normalization data and rename it to norm1, norm2
- Use the following settings to generate `Plot_1`
- Use the following settings to generate `Plot_2`
- Now clicking back and forth between `Plot_1` and `Plot_2` should auto update the histogram UI with the numbers used to generate these workspace
> IBM item: [story596](https://ornlrse.clm.ibmcloud.com/ccm/web/projects/Ne …
=> Populate histogram UI from MakeSlice algorithm history

src/shiver/views/data.py, src/shiver/views/generate.py, tests/views/test_raw_data.py
[901](https://ornlrse.clm.ibmcloud.com/ccm/web/projects/Neutron%20Data%20Project%20(Change%20Management)#action=com.ibm.team.workitem.viewWorkItem&id=901)
You should be able to browse to a directory and only files with `.nxs.h5` extension will be shown in the list view. You should be able to select multiple files.
=> Add Raw Data selection widget

src/shiver/models/histogram.py, src/shiver/presenters/histogram.py, src/shiver/views/histogram.py, src/shiver/views/loading_buttons.py, src/shiver/views/workspace_tables.py, tests/data/define_data.py, tests/models/test_load.py, tests/views/test_histogram.py, tests/views/test_loading_buttons.py
- Implement functionality to allow batch loading dataset (data, background and normalization) defined from a Python file (dictionary)
- Add example Python file
- Add corresponding unit tests
To Test
---------
- Clone the feature branch and setup editable install as instructed in Readme.
- Use the load dataset button to load the data definition file from test folder
- since there is only one dataset defined, it will use it by default
- if there are multiple ones, a pop up window will show up to allow selection
- The data and normalization should be set automatically after click okay
> IBM item: [Story592](https://ornlrse.clm.ibmcloud.com/ccm/web/projects/Neutron%20Data%20Project%20(Change%20Management)#action=com.ibm.team.workitem.viewWorkItem&id=59 …
=> Implement load dataset function (Phase 1)

src/shiver/views/generate.py, tests/views/test_generate.py
- implement MDE type widget
- add error handling for generate tab
- add corresponding unit tests
To test
---------
- clone the feature branch and perform editable install as described in Readme
- switch to generate tab
-  click `Save settings` and it should trigger a warning about invalid MDE name
- enter "test" for mde name, and click again, it should trigger an empty path error
- put "/tmp/test#" in path, click again, it should trigger an invalid path error
- click browse and select a folder, the field should be updated, click "Save settings` again, no error should show up.
> IBM item: [Story942](https://ornlrse.clm.ibmcloud.com/ccm/web/projects/Neutron%20Data%20Project%20(Change%20Management)#action=com.ibm.team.workitem.viewWorkItem&id=942)
=> Add MDE type widget in generate tab

src/shiver/models/histogram.py, src/shiver/presenters/histogram.py, src/shiver/views/histogram.py, src/shiver/views/histogram_parameters.py, tests/models/test_symmetry_operations.py, tests/views/test_histogram_button.py
- fix an issue where incorrect symmetry operation is detected, but still leads to shiver crashing.
- allow error messages to be accumulated before popping.
- update corresponding unit tests.
- clone the feature branch and setup the dev env as instructed in Readme.
- Setup data, background, and normalization workspace (use the Load Dataset button to run the pre-defined dataset script)
- Type incorrect symmetries (see below)
- Hit the histogram button, and an error message should popup
- Closing the error message window should not crash shiver.
> IBM item: [Defect1281](https://ornlrse.clm.ibmcloud.com/ccm/web/projects/Neutron%20Data%20Project%20%28Change%20Management%29#action=com.ibm.team.workitem.viewWorkItem&id=1281&tab=gov.ornl.neutron.workitem.defect.tab.overview)
=> Fix error handling for incorrect symmetry operations

src/shiver/models/makeslice.py
Most of the time is spent running MDNorm so just expose its progress.
To test, load the test MDE, using 1D set the step to something small like 0.001, so you have time to see the progress, press Histogram.
[940](https://ornlrse.clm.ibmcloud.com/ccm/web/projects/Neutron%20Data%20Project%20(Change%20Management)#action=com.ibm.team.workitem.viewWorkItem&id=940)
=> Add progress reporting to MakeSlice

src/shiver/models/histogram.py, src/shiver/presenters/histogram.py, src/shiver/views/histogram.py, src/shiver/views/workspace_tables.py, tests/models/test_save.py, tests/views/test_mdh_workspaces.py
- add new capability to allow saving MDH to ASCII data
- update the context menu (more explicit on its functionality)
- Clone and setup the feature branch following instructions layout in Readme.
- Start shiver and use `LoadDataset` to load data, setup histogram parameters and press `Histogram`.
- Right click on `Plot_1` and select `Save ASCII Data`
- Select path and save the data to disk.
- Verify that the data is saved to disk.
> IBM item: [Story1288](https://ornlrse.clm.ibmcloud.com/ccm/web/projects/Neutron%20Data%20Project%20%28Change%20Management%29#action=com.ibm.team.workitem.viewWorkItem&id=1288)
=> Implement saving data to ASCII

environment.yml, src/shiver/views/data.py, src/shiver/views/generate.py, src/shiver/views/oncat.py, tests/views/test_oncat.py, tests/views/test_sample_parameters_buttons.py
- New OnCat widget is added to allow Shiver to retrieve metadata from OnCat.
- Corresponding unit tests.
- Cross widget connection between data selection and OnCat widget.
- Clone and setup the feature branch as instructed in the description.
- Start the application and go to the generate page
- first time, the connection status should be in red.  Once logged in, a token will be saved and shiver can used to automatically connect to OnCat within 24h.
- click `connect to Oncat` and type in UCAM
- now you should be able to navigate between different instrument, ipts and dataset from the oncat widget. If on analysis cluster, the data widget will also be auto updated if files can be found.
The unit test  `tests/views/test_sample_parameters_buttons.py` …
=> OnCat widget

src/shiver/models/generate.py, src/shiver/models/histogram.py, src/shiver/presenters/generate.py, src/shiver/presenters/histogram.py, src/shiver/views/advanced_options.py, src/shiver/views/data.py, src/shiver/views/generate.py, src/shiver/views/histogram.py, src/shiver/views/reduction_parameters.py, src/shiver/views/workspace_tables.py, tests/models/test_generate_model.py, tests/views/test_advanced_options_inputs.py, tests/views/test_raw_data.py, tests/views/test_reduction_parameters_inputs.py
Description
---------------
- Context menu of MDE workspace, `provenance` will now automatically populate the generate tab if it is created with Shiver.
- Fix an issue where advanced option settings are not properly cached and restored.
- Implement the `generate_mde` support for the load from script option where Shiver will try to generate the MDE if the file cannot be found on disk.
- Switch most dictionary accessor to use `.get` method for a more permissive approach.
Testing Instructions
-------------------------
- Clone the feature branch and perform editable install following instructions from Readme.
- Create an MDE workspace with some settings.
- Create another MDE workspace with different settings.
- In the main tab, click on the workspace …
=> Implement MDE provenance feature for MDE workspace

src/shiver/models/histogram.py, src/shiver/views/loading_buttons.py, tests/models/test_histogram_saving.py
The script generated by Shiver now can be run in Mantid. It should look something like
```python
import shiver
from mantid.simpleapi import LoadNexusProcessed, GenerateDGSMDE, MakeSlice, LoadMD
GenerateDGSMDE(Filenames="/home/3y9/Shiver/tests/data/raw/HYS_178923.nxs.h5",
Type="Background (angle integrated)",
UBParameters="{}",
OutputWorkspace="t")
GenerateDGSMDE(Filenames="/home/3y9/Shiver/tests/data/raw/HYS_178921.nxs.h5,/home/3y9/Shiver/tests/data/raw/HYS_178922.nxs.h5",
UBParameters="{}",
OutputWorkspace="t0")
LoadNexusProcessed(Filename="/home/3y9/Shiver/tests/data/normalization/TiZr.nxs",
OutputWorkspace="TiZr",
LoadHistory="0")
MakeSlice(InputWorkspace="t0",
BackgroundWorkspace="t",
NormalizationWorkspace="TiZr",
Dimension0Binning="0.1",
Dimension3Name="DeltaE",
Smoothing="0", …
```
=> Clean up script generation

src/shiver/__init__.py, src/shiver/shiver.py, tests/models/test_configuration.py
The initialization of configuration mechanism is moved to shiver.py to include the case of starting Shiver from Mantidworkbench
=> Configuration Initialization moved to shiver.py

src/shiver/models/histogram.py
Check if functions exist in ADSObserver before calling them.
Test in mantidworkbench.
=> Issue with ADSObserver functions

conda.recipe/meta.yaml, docs/source/conf.py, environment.yml
- pyoncat added as a conda package 
- some extra comments removed in conf.py
*Note:
Add the channel for pyoncat before installation:
conda config --add channels oncat
=> Pyoncat conda

pyproject.toml, src/shiver/__init__.py, src/shiver/shiver.py
You should now be able to run
```python
python -c "from shiver import __version__; print(__version__)"
```
without a bunch of other stuff being printed
=> Move code around so that you can get the version without importing Mantid

environment.yml
In this PR, the `environment.yml` file was modified to remove pip under the dependencies and also the dependencies that previously employed pip to be pulled. They have now been moved and a few packages have been added in order to address some **errors** that were given by mamba:
According to this, the following packages were added:
- gtk3
- libstdcxx-ng
**For Testing**, the original build environment was deleted and after the modification of the environment.yml file. the environment was re-built and then dependencies installed. Pytest was run with the env activated and as well as the application. All seemed to function correctly other than the errors that were given during the env build step.
=> Made updates to environment.yml. (FOR EWM 2602)

src/shiver/models/generate.py, src/shiver/models/histogram.py, src/shiver/models/makeslices.py, src/shiver/presenters/histogram.py, src/shiver/views/histogram_parameters.py, src/shiver/views/polarized_options.py, src/shiver/views/reduction_parameters.py, src/shiver/views/workspace_tables.py, tests/models/test_histogram_saving.py, tests/views/test_mde_workspaces.py, tests/views/test_polarized_options.py, tests/views/test_reduction_parameters_inputs.py
The code has the following:
1. The polarization dialog appears in the mde workslace list in the main tab. In this case the parameters:             
"PolarizationState",
"PolarizationDirection",
"FlippingRatio",
"FlippingRatioSampleLog",
"PSDA",  are saved as sample logs in the workspace. PSDA appears as a readonly field.
3. In the Generate tab for a specific mde workspace, the polarization parameters are retrieved from the corresponding sample logs. They are saved as separate sample logs on "Generate" button click.
4. Code restructure. Internal functions in histogram model, pass around workspace name over the actual workspace.
5. Sample log PolarizationDirection = "Pz", set as default for NSF and SF polarized workspaces. The sample log is saved, when the polarization state is only saved …
=> Polarization dialog - Parameter storage in the workspace

src/shiver/models/generate.py, src/shiver/models/histogram.py, src/shiver/models/polarized.py, src/shiver/models/sample.py, src/shiver/presenters/histogram.py, src/shiver/presenters/polarized.py, src/shiver/presenters/sample.py, src/shiver/views/generate.py, src/shiver/views/mainwindow.py, src/shiver/views/polarized_options.py, src/shiver/views/reduction_parameters.py, src/shiver/views/sample.py, src/shiver/views/workspace_tables.py, tests/models/test_histogram_saving.py, tests/models/test_sample_parameters_invalid_inputs.py, tests/views/test_mainwindow.py, tests/views/test_mde_workspaces.py, tests/views/test_polarized_options.py
Changes included:
- "Save Workspace" MDE workspace list button
- Sample and Polarization Options refactoring; all related polarization functions are part of Polarized MVP-based structure
- On workspace change in Main tab, the same workspace's Provenance tab closes (if it exists)
- Changes on sample parameters, polarization options and mde name parameter population in main and generate/provenance tabs
- Current tests updated and new ones added
=> Workspace Data Consistency between Main and Generate/Provenance Tabs

src/shiver/views/plots.py, src/shiver/views/workspace_tables.py, tests/views/test_mdh_workspaces.py
Fixes [2813](https://ornlrse.clm.ibmcloud.com/ccm/web/projects/Neutron%20Data%20Project%20(Change%20Management)#action=com.ibm.team.workitem.viewWorkItem&id=2813)
Steps to reproduce:
1. In your local machine: ~/.shiver/configuration.ini set: display_title = full and/or logarithmic_intensity = True
1. In the Histogram tab, fill in the parameters to create a histogram (1D or 2D preferably).
1. Click the"Histogram button". If display_title = full , the plot title contains some extra information on the dimensions. If logarithmic_intensity set to True the plot is show in logarithmic scale
1. Right-click on the histogram title at the "Histogram data in memory" tab. The same title and/or logarithmic scale does not appear.
=> Fix log plots

src/shiver/models/refine_ub.py, src/shiver/views/refine_ub.py, tests/models/test_refine_ub.py
The correct Mantid algorithm to keep the indexation is OptimizeLatticeForCellType.
Also, from the matplotlib documentation:
```
Note that matplotlib.pyplot.tight_layout() will only adjust the subplot params when it is called. 
In order to perform this adjustment each time the figure is redrawn, you can call fig.set_tight_layout(True)
```
=> Use the Optimize instead of Select

src/shiver/views/advanced_options.py, tests/models/test_makeslices.py, tests/views/test_advanced_options_inputs.py
E_max and E_min are already stored as string in the dict so we don't need to convert back to string, this also fix 'None' being set as the E_max/E_min.
I also updated test_make_slices_invalid after changes from mantidproject/mantid/pull/36563
Fixes [EWM3586](https://ornlrse.clm.ibmcloud.com/ccm/web/projects/Neutron%20Data%20Project%20(Change%20Management)#action=com.ibm.team.workitem.viewWorkItem&id=3586)
=> Fix 'None' being set as E_max and E_min

src/shiver/models/histogram.py, src/shiver/presenters/histogram.py, src/shiver/views/histogram.py, src/shiver/views/workspace_tables.py, tests/models/test_histogram_saving.py, tests/views/test_mde_workspaces.py
Adds an action to clone and scale MDE Workspaces
=> Add clone and scale MDE Workspace actions

environment.yml, src/shiver/configuration_template.ini, src/shiver/models/convert_dgs_to_single_mde.py, src/shiver/models/generate_dgs_mde.py, src/shiver/models/histogram.py, src/shiver/models/sample.py, src/shiver/presenters/sample.py, src/shiver/views/sample.py, tests/models/test_generatemde.py, tests/models/test_histogram_saving.py, tests/models/test_sample_parameters_buttons_actions.py, tests/views/test_sample_parameters_buttons.py
The code includes the following changes:
* set facility to SNS (some cleanup too)
* add algorithms to Shiver category in Mantidworkbench
* save sample logs in the mdhistogram with options set in the config file
* change Mantid version in conda environment
* load UB from nexus for mdworkspaces.
* save UB as ISAW
* imports of Mantid algorithms defined in Shiver for pytest to avoid crashes of single tests
Related tests are added.
=> Facility Set - Sample Log Saving - Save/LoadUB - Imports and minor issues

src/shiver/models/histogram.py, tests/models/test_histogram_saving.py
Updates the sample log when a scale factor is applied
=> Sample log - MDScale

src/shiver/models/generate_dgs_mde.py, tests/models/test_generate_model.py, tests/models/test_generatemde.py
Minor issue that parameters are resolved as strings
`getPropertyValue` for `False` will return `"0"`, which evaluates to True. Using `getProperty("PropertyName").value` returns a bool.
Similarly, the `mask_btp_inputs` is a string `"[]"` which evaluates to True
=> Minor issue that parameters are resolved as strings

src/shiver/models/polarized.py, src/shiver/models/refine_ub.py, src/shiver/models/sample.py, src/shiver/presenters/polarized.py, tests/models/test_histogram_saving.py, tests/models/test_refine_ub.py, tests/models/test_sample_parameters_buttons_actions.py, tests/views/test_refine_ub_ui.py
The code contains changes related to MDEConfig SampleLog. The MDEConfig is updated for Sample Parameters and Polarization Options every time the values are updated (Sample Parameters Dialog, Polarization Dialog and Refine UB tab), if there is an existing MDEConfig in the workspace.
Related tests added/updated.
=> MDEConfig update for Sample Parameters and Polarization Options

environment.yml, src/shiver/views/oncat.py, tests/conftest.py, tests/views/test_oncat.py
Update Shiver to use the new [https://github.com/neutrons/pyoncatqt](pyoncatqt) login widget
This is a widget that is created to provide a standardized baseline for logging into and interacting with ONCat. This will provide the same functionality as before and should cause no noticeable changes to the users. 
Tests at tests/view/test_oncat.py have been updated for the new functionality. To manually test this change, start shiver and login to oncat to verify it works as expected.
=> update oncat login

src/shiver/views/oncat.py, tests/views/test_oncat.py
Shiver crashes when selecting i.e. IPTS-4653 due to the "metadata" in datafiles missing keys. The changes wrapped the part of the code that would crashes with try: except commands such that if "metadata"=={} the function returns an empty list. A unit test is also added for this scenario.
=> Oncat issue

src/shiver/views/oncat.py, tests/views/test_oncat.py
Users complained that it takes too long to go to the current IPTS
=> Reverse ipts order in the GUI

src/shiver/models/convert_dgs_to_single_mde.py, src/shiver/models/sample.py, tests/models/test_generatemde.py, tests/models/test_sample_parameters_buttons_actions.py
Pause was not handled correctly. In the test it would have killed all events, and it would crash on ConvertToMD.
The sample dialog would crash if no UB is already present in the workspace
=> Fix errors in handling pause, and MD workspaces with no UB

environment.yml
The CI currently fails on next, see https://github.com/neutrons/Shiver/actions/runs/12366078528
Test is failing because https://github.com/spyder-ide/qtpy/issues/505 so lets avoid qtpy=2.4.2
I don't know why the wheel package need to be explicitly included when previously it didn't.
=> Fix CI, failing test and missing wheel package

.github/workflows/actions.yml, environment.yml, src/shiver/models/corrections.py, src/shiver/presenters/histogram.py, src/shiver/views/corrections.py, src/shiver/views/oncat.py, tests/conftest.py, tests/views/test_correction.py
Ref: [8609: Add Magnetic structure factor correction to Shiver](https://ornlrse.clm.ibmcloud.com/ccm/resource/itemName/com.ibm.team.workitem.WorkItem/8609)
The MagneticFormFactorCorrectionMD algorithm was only just added to mantid so you will need the mantid nightly version `>6.11.20241216.1838` for this to work. This also means a new version of matplotlib and move to numpy 2.0.
I also fixed the codecov reporting which hasn't updated in 11 months so the diff is probably not accurate.
The "Magnetic structure factor" correction should now be enables.
You should be able to select which ion to use.
The workspace name should be appened with "_MSF"
If you plot them you can see the difference.
+ [ ] clearly named variables …
=> Add magnetic structure factor correction

src/shiver/configuration.py, src/shiver/configuration_template.ini, src/shiver/presenters/refine_ub.py, src/shiver/views/oncat.py, tests/conftest.py, tests/models/test_configuration.py, tests/views/test_oncat.py
related PR: https://github.com/neutrons/pyoncatqt/pull/9 
oncat connectivity status logic update, configuration mechanism and client id
The code includes the following:
- oncat connectivity status appears only for 5 seconds
- ocan login dialog pops up at button pressing at any time
- client id update
- configuration mechanism with inclusion of version. Version is retrieved from \__version\__ and written to the user's configuration file. If user's version does not exist or different that current software version all configruation variables are updated, else it works as before.
- tests updated/new for the logic
- refine ub update with group attribute, due to Mantid changes
+ [ ] clearly named variables (better to be …
=> Oncat connectivity status +configuration mechanism

src/shiver/models/generate_dgs_mde.py, tests/models/test_generatemde.py
singlee quotes in values for json.loads in Generatemde were replaces with double quotes.
test added
[[Shiver] Json double quotes in generate mde](https://ornlrse.clm.ibmcloud.com/ccm/resource/itemName/com.ibm.team.workitem.WorkItem/9467)
=> Generatemde single quotes replaced by double for json

environment.yml, pyproject.toml, src/shiver/views/oncat.py, tests/views/test_oncat.py
This or fixes the defect of not grouping files based on s2 angle. This only applies to HYSPEC when the detector moves during experiment.
Additional tests were also added to capture this behaviour. 
EWM [9809](https://ornlrse.clm.ibmcloud.com/ccm/web/projects/Neutron%20Data%20Project%20(Change%20Management)#action=com.ibm.team.workitem.viewWorkItem&id=9809)
=> Grouping runs based on s2

environment.yml, src/shiver/models/corrections.py, src/shiver/models/histogram.py, src/shiver/presenters/histogram.py, src/shiver/views/corrections.py, tests/models/test_corrections.py, tests/models/test_histogram_saving.py, tests/models/test_load.py, tests/views/test_correction.py
This PR adds debye-waller factor to shiver. It also fixes a bug where renaming workspace crashes shiver.
EWM [9412](https://ornlrse.clm.ibmcloud.com/ccm/web/projects/Neutron%20Data%20Project%20(Change%20Management)#action=com.ibm.team.workitem.viewWorkItem&id=9412)
EWM [10033
](https://ornlrse.clm.ibmcloud.com/ccm/web/projects/Neutron%20Data%20Project%20(Change%20Management)#action=com.ibm.team.workitem.viewWorkItem&id=10033)
To test, load some data with quasi-flat excitations and observe that the intensity scales exponentially at increased |Q| based on <U^2>.
left side is original data, right side debye-waller normalized.
+ [ ] code comments …
=> Debye-waller

src/shiver/views/refine_ub.py, tests/views/test_refine_ub_ui.py
The code updates the refine_ub figure so the mantid workbench toolbar is not added and thus creating issue.
An indirect test is added that checks the figure's callbacks.
EWM [RuntimeError is displayed in MantidWorkbench, when user hovers on the refine ub's (right 3) plots](https://ornlrse.clm.ibmcloud.com/ccm/resource/itemName/com.ibm.team.workitem.WorkItem/5317)
=> Mantidworkbench plot error

.codecov.yml, src/shiver/configuration.py, src/shiver/models/generate_dgs_mde.py, tests/models/test_configuration.py
Fixed issues finding Ei/T0
With keeep_logs configuration set to False, vChTrans log item needed on ARCS and SEQUOIA is missing. Also, in Background minimized by angle and energy, one needs to load the monitors (can only get Ei/T0 from data in case of CNCS and HYSPEC)
To test:
* Generate a 128*8 grouping for ARCS
* Select files ARCS_300975 to 980 in IPTS-34518
* Generate a background minimized by angle and energy
=> Fix issue with finding Ei/T0 for background
