reduce_data_to_MDE.py

provides the capability to ingest a dictionary in the Runs key of the form {'file': '<filename.json>', 'ky': '<str>'}. where <str> is the key to the field in the json file that contains a list of lists of run numbers

allow adding file lists from a json file

---

define_data_example1.py

Added a more descriptive comment to help avoid users changing reduce to MDE.py

added explanation of Energy transfer limits

---

slice_utils.py

add utilities for making a plot with parameters

 added plot with parameters

---

.github/workflows/actions.yml

This tiny PR update the branch mapper to v2.

update branch mapper to v2

---

src/shiver/__init__.py
src/shiver/models/histogram.py
src/shiver/presenters/histogram.py
src/shiver/views/histogram.py
src/shiver/views/loading_buttons.py
tests/models/test_load.py
tests/views/test_loading_buttons.py

[591](https://ornlrse.clm.ibmcloud.com/ccm/web/projects/Neutron%20Data%20Project%20%28Change%20Management%29#action=com.ibm.team.workitem.viewWorkItem&id=591)
I haven't yet implemented the check is the loaded workspace is the correct type, that will come later.
To Test:
Start shiver from the mantidworkbench, press either "Load MDE" or "Load normalization" and select a file. The if the is correct type if should be loaded and appear in the workspace table otherwise an error message should appear.

Add loading to the Load buttons

---

src/shiver/models/histogram.py
src/shiver/presenters/histogram.py
src/shiver/views/histogram.py
src/shiver/views/workspace_tables.py
tests/views/test_mde_workspaces.py

[962](https://ornlrse.clm.ibmcloud.com/ccm/web/projects/Neutron%20Data%20Project%20(Change%20Management)#action=com.ibm.team.workitem.viewWorkItem&id=962)

Add custom icons to show Q_sample, Q_lab, selected data and background

---

src/shiver/views/histogram.py
src/shiver/views/workspace_tables.py
tests/views/test_histogram.py

[1002](https://ornlrse.clm.ibmcloud.com/ccm/web/projects/Neutron%20Data%20Project%20(Change%20Management)#action=com.ibm.team.workitem.viewWorkItem&id=1002)

Add rename/delete menu to normalization table

---

src/shiver/__init__.py
src/shiver/models/histogram.py
src/shiver/presenters/histogram.py
src/shiver/views/histogram.py
src/shiver/views/workspace_tables.py
tests/views/test_histogram.py
tests/views/test_mde_workspaces.py
tests/views/test_mdh_workspaces.py

- Plot/Overplot
- Save Script
- Save Data
- Delete
[598](https://ornlrse.clm.ibmcloud.com/ccm/web/projects/Neutron%20Data%20Project%20(Change%20Management)#action=com.ibm.team.workitem.viewWorkItem&id=598)
To Test:
Create valid MDHistoWorkspace with different dimensions, right-click plot to see different behaviour
_e.g._
```python
from mantid.simpleapi import CreateMDHistoWorkspace
CreateMDHistoWorkspace(
Dimensionality=4,
Extents="-10,10,-1,1,-1,1,-1,1",
SignalInput=range(100),
ErrorInput=[1] * 100,
NumberOfBins="100,1,1,1",
Names=["[H,0,0]", "[0,K,L]", "[0,0,L]", "DeltaE"],
Units="in 1 A^-1,in 1 A^-1,in 1 A^-1,meV",
Frames="HKL,HKL,HKL,General Frame",
OutputWorkspace="Plot 1D",
)
CreateMDHistoWorkspace(
Dimensionality=4,
Extents="-10,10,-1,1,-1,1,-1,1",
SignalInput=range(100, 0, -1), …
```

Add menu for histograms

---

src/shiver/views/generate.py

This should allow people to work on an individual widget with fewer conflicts.

Add basic layout to Generate tab

---

environment.yml
src/shiver/presenters/histogram.py
src/shiver/views/mainwindow.py
src/shiver/views/sample.py

Update URL and move to nightly mantid.

Disable generate tab for first release

---

tests/models/test_histogram_saving.py

I forgot to `git add` this as part of #50

Add test for histogram saving that I wrote for #50 but I forgot to add

---

src/shiver/models/sample.py
src/shiver/views/advanced_options.py
src/shiver/views/generate.py
src/shiver/views/reduction_parameters.py
src/shiver/views/sample.py
src/shiver/views/workspace_tables.py
tests/views/test_advanced_options_inputs.py
tests/views/test_reduction_parameters_inputs.py
tests/views/test_sample_parameters_buttons.py
tests/views/test_sample_parameters_inputs.py

- Reduction Parameters Widget in the Generate tab.
All buttons except for "Polarized Options" should work.
- Advanced Parameters dialog. 
The dialog pops-up on  "Advanced Options" button click.

Reductparams

---

environment.yml
src/shiver/__init__.py
src/shiver/models/ConvertDGSToMDE.py
src/shiver/models/ConvertDGSToSingleMDE.py
src/shiver/models/GenerateDGSMDE.py
src/shiver/models/utils.py
src/shiver/shiver.py
tests/conftest.py
tests/models/test_generatemde.py
tests/models/test_utils.py
tests/views/test_raw_data.py

Creates algorithms to convert to MDE

Convert to mde

---

.pre-commit-config.yaml
src/shiver/__init__.py
src/shiver/models/convert_dgs_to_single_mde.py
src/shiver/models/generate_dgs_mde.py
src/shiver/views/histogram_parameters.py
src/shiver/views/loading_buttons.py
src/shiver/views/mainwindow.py
src/shiver/views/workspace_tables.py

[1366](https://ornlrse.clm.ibmcloud.com/ccm/web/projects/Neutron%20Data%20Project%20%28Change%20Management%29#action=com.ibm.team.workitem.viewWorkItem&id=1366)

Update labels and add MDE table legend

---

src/shiver/models/sample.py
src/shiver/presenters/sample.py
src/shiver/views/advanced_options.py
src/shiver/views/histogram_parameters.py
src/shiver/views/polarized_options.py
src/shiver/views/reduction_parameters.py
src/shiver/views/sample.py
tests/models/test_sample_parameters_buttons_actions.py
tests/models/test_sample_parameters_invalid_inputs.py
tests/views/test_advanced_options_inputs.py
tests/views/test_polarized_options.py
tests/views/test_reduction_parameters_inputs.py
tests/views/test_sample_parameters_buttons.py
tests/views/test_sample_parameters_inputs.py

This is part of the reduction parameters widget
Polarized Options Dialog on clicking the "Polarization Options" button:
Changes on getting all fields values as a dictionary and populating all parameters from a dictionary for:
- Reduction parameters
- Sample Parameters (data initialization updates)
- Advanced Options
- Polarized Options

Pol options

---

tests/views/test_sample_parameters_buttons.py

I can not reproduce the issue. Checking to see what the CI does.
[1386](https://ornlrse.clm.ibmcloud.com/ccm/web/projects/Neutron%20Data%20Project%20(Change%20Management)#action=com.ibm.team.workitem.viewWorkItem&id=1386)

Unskip test

---

src/shiver/views/workspace_tables.py
tests/views/test_mde_workspaces.py

[1365](https://ornlrse.clm.ibmcloud.com/ccm/web/projects/Neutron%20Data%20Project%20(Change%20Management)#action=com.ibm.team.workitem.viewWorkItem&id=1365)

Change MDE workspace selection to left-click and set selected items in list

---

src/shiver/models/generate.py
src/shiver/presenters/generate.py
src/shiver/views/advanced_options.py
src/shiver/views/generate.py
tests/models/test_generate_model.py
tests/views/test_advanced_options_inputs.py

Description
--------------
- add model to call generate MDE algorithm
- connect view and model
- add new unit tests
- disable a few features that will irritate users
How to Test
---------------
1. Clone the feature branch and perform editable install as instructed in README.md
2. Switch to generate tab
4. Click save settings button
- a new Python file, `test.py` should be generated 
6. Click generate button
- the `test` workspace should show up 
> IBM item: [Story937](https://ornlrse.clm.ibmcloud.com/ccm/web/projects/Neutron%20Data%20Project%20(Change%20Management)#action=com.ibm.team.workitem.viewWorkItem&id=937)

Implement generate MDE widget

---

src/shiver/models/histogram.py
src/shiver/presenters/histogram.py
src/shiver/views/histogram.py
src/shiver/views/plots.py
src/shiver/views/workspace_tables.py
tests/views/test_histogram.py

* After histogramming is completed, the default plot for the histogram will be created
* The histogram UI input widgets will be disabled while the algorithm is running
[1373](https://ornlrse.clm.ibmcloud.com/ccm/web/projects/Neutron%20Data%20Project%20(Change%20Management)#action=com.ibm.team.workitem.viewWorkItem&id=1373)

Update histogramming behaviour

---

src/shiver/models/sample.py
src/shiver/presenters/histogram.py
src/shiver/views/advanced_options.py
src/shiver/views/corrections.py
src/shiver/views/generate.py
src/shiver/views/histogram_parameters.py
src/shiver/views/polarized_options.py
src/shiver/views/sample.py
tests/models/test_sample_parameters_invalid_inputs.py
tests/views/test_advanced_options_inputs.py
tests/views/test_correction.py
tests/views/test_polarized_options.py
tests/views/test_sample_parameters_inputs.py

Error handling updates with border-color and button "Apply" (de)/activations and error messages from models.
The following screens are updated:
- Sample Parameters 
- Advanced Options
- Polarization Options
- Corrections Tab
Related tests updates are included.

Err msg 02

---

src/shiver/models/generate_dgs_mde.py
src/shiver/views/generate.py
tests/models/test_generatemde.py

"Background (angle integrated)" option should now work

Fix background generation

---

src/shiver/views/data.py
src/shiver/views/generate.py
src/shiver/views/loading_buttons.py
src/shiver/views/reduction_parameters.py
src/shiver/views/sample.py
src/shiver/views/workspace_tables.py

This fixes a bug with the testing when using gnome and newer versions of pyqt

Change QFileDialog to not use Native Dialog

---

src/shiver/models/histogram.py
src/shiver/presenters/histogram.py
src/shiver/views/data.py
src/shiver/views/histogram.py
src/shiver/views/histogram_parameters.py
src/shiver/views/loading_buttons.py
src/shiver/views/oncat.py
src/shiver/views/plots.py
src/shiver/views/workspace_tables.py
tests/models/test_plot_display_name.py
tests/views/test_dimensions.py
tests/views/test_oncat.py
tests/views/test_plots.py

The code has the following 
Updates:
- A new field is added in Histogram Parameters section labeled: 'Intensity'. It contains minimum and maximum values. Neither, both and one of them are allowed. The values are used to set appropriate limits for 1D, 2D, 3D and 4D plots.
- Display titles for 1D and 2D plots are updated to include min and max values of the corresponding dimensions.
- Progress Bar is updated when loading files.
- Load Buttons are reordered
Code restructures:
- invalid styles are imported everywhere the same
Minor Bug fixes:
- Oncat directory schema check
Additional tests are included.

Main Tab UI - Changes

---

conda.recipe/meta.yaml
environment.yml
pyproject.toml
setup.py

parameter re-definition/structure for conda package creation.

Parameters for Conda Package

---

pyproject.toml
src/shiver/models/convert_dgs_to_single_mde.py
src/shiver/models/generate.py
src/shiver/models/generate_dgs_mde.py
src/shiver/views/generate.py
src/shiver/views/minimise_background.py
src/shiver/views/minimize_background.py
src/shiver/views/reduction_parameters.py
tests/data/HYS_groups.xml
tests/models/test_generatemde.py
tests/views/test_generate.py
tests/views/test_minimize_background.py

This PR requires https://github.com/mantidproject/mantid/pull/35971 to be merged first before all tests will pass
This enables the "Background (minmized by angle and energy)" within Shiver using the new GenerateGoniometerIndependentBackground algorithm
Example using the test data
Ref [2201](https://ornlrse.clm.ibmcloud.com/ccm/web/projects/Neutron%20Data%20Project%20(Change%20Management)#action=com.ibm.team.workitem.viewWorkItem&id=2201)

Enable Background minimized by angle and energy

---

src/shiver/configuration.py
src/shiver/configuration_template.ini
src/shiver/views/histogram.py
src/shiver/views/plots.py
tests/models/test_configuration.py
tests/views/test_plots.py

The display title for plot default values and functionality are updated.
The configuration mechanism and related tests are updated, too.

Configuration plot - display title updates

---

.github/workflows/actions.yml

actions.yml updated to use micromamba for overcoming CI issues .
channels are duplicated in environment.yml and actions.yml

Github Actions Update

---

src/shiver/shiver.py
tests/models/test_configuration.py
tests/models/test_show_version.py

User can print Shiver's current version from command line with --v or --version.
Tests were added.

Show version

---

docs/source/repo_doc.rst

Additional files were included in the repo_docs.rst for readthedocs website.

Read the docs modules updated

---

.github/workflows/actions.yml

trigger-deploy step is in comments, because it is currently not working.

Github actions: trigger-deploy in comments

---

conda.recipe/meta.yaml
environment.yml
pyproject.toml

It includes dependency version updates, due to changes mainly in Mantid and pyoncatqt, before we do a new release/ release candidate.

Conda dependecy upgrades

---

conda.recipe/meta.yaml
pyproject.toml

meta dependency removal due to no dependency resolution

Depedency version removal

---

src/shiver/configuration.py
src/shiver/configuration_template.ini
src/shiver/models/convert_dgs_to_single_mde.py
src/shiver/models/generate_dgs_mde.py
tests/models/test_configuration.py
tests/models/test_generatemde.py
tests/models/test_load.py

Remove unnecessary logs. This is controlled by the configuration

Remove logs

---

environment.yml

use ornl version of mantid and prod pyoncat

---

src/shiver/views/workspace_tables.py
tests/views/test_mde_workspaces.py

Fixing a defect [10863](https://ornlrse.clm.ibmcloud.com/ccm/web/projects/Neutron%20Data%20Project%20(Change%20Management)#action=com.ibm.team.workitem.viewWorkItem&id=10863)

Index error

---

README.md

README CI status
